SUPER_CONFIG_PATH:

MODE:       # "train" or "eval" or "submit", for the main.py script.

# System config, like CPU/GPU
NUM_CPU_PER_GPU:          # number of CPU per GPU
NUM_WORKERS: 1
DEVICE: cuda
AVAILABLE_GPUS: '0'

# Git version:
GIT_VERSION:              # you should input the git version here, if you are using wandb to log your experiments.

# Datasets:
DATASETS: [DanceTrack]    # for joint training, there may be multiple datasets, like: [CrowdHuman, MOT17]
DATASET_SPLITS: [train]   # and corresponding splits, like: [train, val]
DATA_ROOT: ./datasets/    # datasets root
# Sampling settings:
SAMPLE_STEPS: [0]
SAMPLE_LENGTHS: [5]
SAMPLE_MODES: [random_interval]
SAMPLE_INTERVALS: [5]
# Data augmentation setting:
AUG_OVERFLOW_BBOX: False
AUG_REVERSE_CLIP: 0.0
AUG_RANDOM_SHIFT_MAX_RATIO: 0.06    # Only for static images

# Model settings:
NUM_ID_VOCABULARY: 60
NUM_CLASSES: 1
MAX_TEMPORAL_LENGTH: 5
ID_LOSS_WEIGHT: 1
ID_LOSS_GPU_AVERAGE: True
ID_DECODER_LAYERS: 6
SEQ_NUM_HEADS: 8

# Backbone:
BACKBONE: resnet50
DILATION: False
depth: 50
variant: d
freeze_at: 0
return_idx: [1, 2, 3]
num_stages: 4
freeze_norm: True
pretrained: True

# About DETR-Framework
DETR_NUM_QUERIES: 300
DETR_NUM_FEATURE_LEVELS: 4
DETR_AUX_LOSS: True
DETR_WITH_BOX_REFINE: True
DETR_TWO_STAGE: False
DETR_MASKS: False
DETR_PE: sine
DETR_ENC_LAYERS: 1
DETR_DEC_LAYERS: 6
DETR_NUM_HEADS: 8
DETR_DROPOUT: 0.0
DETR_DEC_N_POINTS: 4
DETR_ENC_N_POINTS: 4
DETR_BBOX_LOSS_COEF: 5.0
DETR_GIOU_LOSS_COEF: 2.0
DETR_FOCAL_ALPHA: 0.25
DETR_PRETRAIN:
# Training Setting:
TRAIN_STAGE: joint
SEED: 42
USE_DISTRIBUTED: False
DETR_NUM_TRAIN_FRAMES: 5
# Below two parameters are for memory optimized DETR training:
DETR_CHECKPOINT_FRAMES: 2
SEQ_DECODER_CHECKPOINT: False
# Training Augmentation:
TRAJ_DROP_RATIO: 0.5
TRAJ_SWITCH_RATIO: 0.3
# Training Scheduler:
EPOCHS: 14
LR: 1.0e-4
LR_BACKBONE_NAMES: [backbone]
LR_BACKBONE_SCALE: 0.1

LR_LINEAR_PROJ_NAMES: [reference_points, sampling_offsets]
LR_LINEAR_PROJ_SCALE: 0.1

WEIGHT_DECAY_NAMES: ['^(?=.*encoder(?=.*bias|.*norm.*weight)).*$', '^(?=.*decoder(?=.*bias|.*norm.*weight)).*$']

LR_WARMUP_EPOCHS: 1
WEIGHT_DECAY: 0.0001
CLIP_MAX_NORM: 0.1
SCHEDULER_TYPE: MultiStep
SCHEDULER_MILESTONES: [20,24]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 3
GROUP_NUM: 1
ACCUMULATE_STEPS: 2
RESUME_MODEL:
RESUME_OPTIMIZER: True
RESUME_SCHEDULER: True
RESUME_STATES: True

# Inference:
INFERENCE_MODEL:
INFERENCE_ONLY_DETR: False
INFERENCE_DATASET: DanceTrack
INFERENCE_SPLIT: val
INFERENCE_CONFIG_PATH:          # mostly, you don't need to set this parameter. See submit_engine.py L34 for more details.
INFERENCE_GROUP:
INFERENCE_ENSEMBLE: 0
# Thresholds:
ID_THRESH: 0.2
DET_THRESH: 0.2
NEWBORN_THRESH: 0.2
AREA_THRESH: 100

# Outputs:
OUTPUTS_DIR:
OUTPUTS_PER_STEP: 100
SAVE_CHECKPOINT_PER_EPOCH: 1
USE_TENSORBOARD: True
USE_WANDB: True
PROJECT_NAME: RTMOT
EXP_NAME: r50_rt_detr_motip_dancetrack
EXP_GROUP: default
EXP_OWNER: hellorpg

# Settings which are used to reduce the memory usage of DETR criterion.
# Too many objects (such as CrowdHuman) may cause OOM error.
MEMORY_OPTIMIZED_DETR_CRITERION: False
AUTO_MEMORY_OPTIMIZED_DETR_CRITERION: False
CHECKPOINT_DETR_CRITERION: False

DETR_FRAMEWORK: RT-DETR
#DETR_PRETRAIN: None #./pretrains/r50_dab_deformable_detr_coco_dancetrack.pth

# Different dimension settings for DAB DETR:
DETR_HIDDEN_DIM: 256
DETR_DIM_FEEDFORWARD: 2048
SEQ_HIDDEN_DIM: 256
SEQ_DIM_FEEDFORWARD: 1024

# From DAB DETR training settings:
DETR_CLS_LOSS_COEF: 1.0
DETR_SET_COST_CLASS: 2.0

# Larger image size, align with previous researches, like MOTR, MeMOTR, etc.


AUG_RESIZE_SCALES: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800] # [640]
AUG_MAX_SIZE: 800
AUG_RANDOM_RESIZE: [640,800,960] # [640]
AUG_RANDOM_CROP_MIN: 480
AUG_RANDOM_CROP_MAX: 800
INFERENCE_MAX_SIZE: 640
#AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]
#AUG_MAX_SIZE: 1536
#AUG_RANDOM_RESIZE: [800, 1000, 1200]
#AUG_RANDOM_CROP_MIN: 800
#AUG_RANDOM_CROP_MAX: 1200
#INFERENCE_MAX_SIZE: 1536
multi_scale: # [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]